"""Builds an unmanaged solution package that creates or updates the "Snap Campaign" table
(sanidi_SnapCampaign) in the "AlSanidi | Marketing" solution: columns, choices, alternate
key, main form (with a Related tab listing the campaign's Snap Ad Squads) and views.

Field definitions come from https://developers.snap.com/marketing-api/Ads-API/campaigns.
The package format is described in ../table_builder.py.

Run (import the Snap Ad Squad table first, since the Related tab points at it):
  python3 build_table_solution.py --template <template export zip> [--out SnapCampaignTable.zip]
  pac solution import --path SnapCampaignTable.zip --environment <env> --publish-changes
"""
import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from table_builder import RelatedGrid, TableSpec, build_package, view_id_for  # noqa: E402

DELIVERY_OPTIONSET = "sanidi_snapcampaigndeliverystatus"

DELIVERY_STATUS = [
    "PENDING", "VALID", "DELIVERING", "INVALID_NOT_ACTIVE", "INVALID_NOT_EFFECTIVE_ACTIVE",
    "INVALID_START_TIME", "INVALID_END_TIME", "INVALID_EFFECTIVE_START_TIME", "INVALID_EFFECTIVE_END_TIME",
    "INVALID_EFFECTIVE_DELETED", "INVALID_EFFECTIVE_INVALID", "INVALID_START_TIME_AFTER_END_TIME",
    "INVALID_UNKNOWN", "INVALID_CAMPAIGN_LIFETIME_SPEND_CAP",
    "INVALID_OVER_BUDGET_CAMPAIGN_FINALIZED_LIFETIME_SPEND", "INVALID_OVER_BUDGET_CAMPAIGN_REALTIME_LIFETIME_SPEND",
    "INVALID_OVER_BUDGET_CAMPAIGN_DAILY_SPEND", "NO_VALID_AD_SQUAD", "INVALID_RF_FOR_RESERVED_BUY",
    "INVALID_UNKNOWN_FORECAST_ERROR", "INVALID_CAMPAIGN_HAS_NO_ACTIVE_AD_SQUAD", "INVALID_TEST_ACCOUNT",
]

# (logical name, display name, kind, extra, description); kinds are described in table_builder.py.
FIELDS = [
    ("sanidi_campaignname", "Campaign Name", "text", 375, "Snap: name"),
    ("sanidi_campaignid", "Campaign ID", "text", 100, "Snap: id"),
    ("sanidi_adaccountid", "Ad Account ID", "text", 100, "Snap: ad_account_id"),
    ("sanidi_objective", "Objective", "choice",
     ["BRAND_AWARENESS", "APP_CONVERSION", "APP_INSTALL", "CATALOG_SALES", "ENGAGEMENT", "LEAD_GENERATION",
      "VIDEO_VIEW", "WEB_CONVERSION", "PROMOTE_STORIES", "PROMOTE_PLACES"], "Snap: objective (legacy)"),
    ("sanidi_objectivev2type", "Objective V2 Type", "choice",
     ["AWARENESS_AND_ENGAGEMENT", "SALES", "TRAFFIC", "APP_PROMOTION", "LEADS"],
     "Snap: objective_v2_properties.objective_v2_type"),
    ("sanidi_promotiontype", "Promotion Type", "choice",
     ["PROMOTE_PLACES", "PROMOTE_SHOWS", "APP_INSTALL", "APP_REENGAGEMENT"],
     "Snap: objective_v2_properties.promotion_type"),
    ("sanidi_objectiveautogenerated", "Objective Auto Generated", "bool", None,
     "Snap: objective_v2_properties.is_auto_generated"),
    ("sanidi_status", "Status", "choice", ["ACTIVE", "PAUSED"], "Snap: status"),
    ("sanidi_deliverystatus", "Delivery Status", "multichoice", (DELIVERY_OPTIONSET, DELIVERY_STATUS),
     "Snap: delivery_status"),
    ("sanidi_creationstate", "Creation State", "text", 100, "Snap: creation_state"),
    ("sanidi_deleted", "Deleted", "bool", None, "Snap: deleted"),
    ("sanidi_starttime", "Start Time", "datetime", None, "Snap: start_time"),
    ("sanidi_endtime", "End Time", "datetime", None, "Snap: end_time"),
    ("sanidi_createdat", "Created At", "datetime", None, "Snap: created_at"),
    ("sanidi_updatedat", "Updated At", "datetime", None, "Snap: updated_at"),
    ("sanidi_dailybudget", "Daily Budget", "money", None, "Snap: daily_budget_micro / 1,000,000"),
    ("sanidi_lifetimespendcap", "Lifetime Spend Cap", "money", None, "Snap: lifetime_spend_cap_micro / 1,000,000"),
    ("sanidi_pacinglevel", "Pacing Level", "choice", ["AD_SQUAD", "CAMPAIGN"], "Snap: pacing_level"),
    ("sanidi_pacingpropertiesversion", "Pacing Properties Version", "int", None, "Snap: pacing_properties_version"),
    ("sanidi_buymodel", "Buy Model", "choice", ["AUCTION", "RESERVED"], "Snap: buy_model"),
    ("sanidi_reservedtype", "Reserved Type", "choice", ["REACH_AND_FREQUENCY"], "Snap: reserved_type"),
    ("sanidi_autobidmaxbid", "Auto Bid Max Bid", "money", None, "Snap: auto_bid_max_bid_micro / 1,000,000"),
    ("sanidi_sharedconversionlocation", "Shared Conversion Location", "choice",
     ["APP", "WEB", "CALL", "TEXT", "LEAD_FORM"], "Snap: shared_properties.shared_conversion_location"),
    ("sanidi_sharedconversionwindow", "Shared Conversion Window", "text", 100,
     "Snap: shared_properties.shared_conversion_window"),
    ("sanidi_sharedoptimizationgoal", "Shared Optimization Goal", "text", 100,
     "Snap: shared_properties.shared_optimization_goal"),
    ("sanidi_sharedadsquadbidstrategy", "Shared Ad Squad Bid Strategy", "choice",
     ["AUTO_BID", "LOWEST_COST_WITH_MAX_BID", "TARGET_COST"], "Snap: shared_properties.shared_ad_squad_bid_strategy"),
    ("sanidi_sharedtargetcost", "Shared Target Cost", "money", None,
     "Snap: shared_properties.target_cost_in_micro / 1,000,000"),
    ("sanidi_sharedpixelid", "Shared Pixel ID", "text", 100, "Snap: shared_properties.shared_pixel_id"),
    ("sanidi_iosappid", "iOS App ID", "text", 100, "Snap: measurement_spec.ios_app_id"),
    ("sanidi_androidappurl", "Android App URL", "text", 200, "Snap: measurement_spec.android_app_url"),
    ("sanidi_appoptimizationtype", "App Optimization Type", "choice",
     ["SKAN", "UNIFIED", "UNIFIED_WITH_SKAN_MEASURE"], "Snap: mobile_app_properties.app_optimization_type"),
    ("sanidi_skadnetworkstatus", "SKAdNetwork Status", "choice", ["ENROLLED", "NOT_ENROLLED"],
     "Snap: mobile_app_properties.skad_network_status"),
    ("sanidi_mobileappid", "Mobile App ID", "text", 100, "Snap: mobile_app_properties.mobile_app_id"),
    ("sanidi_catalogid", "Catalog ID", "text", 100, "Snap: product_properties.catalog_id"),
    ("sanidi_restricteddeliverysignals", "Restricted Delivery Signals", "bool", None,
     "Snap: regulations.restricted_delivery_signals"),
    ("sanidi_candidateballotinformation", "Candidate Ballot Information", "text", 500,
     "Snap: regulations.candidate_ballot_information"),
]
F = {f[0]: f for f in FIELDS}

# Main form: tab -> [(section name, label, [fields])]; "ownerid" sits in General like Meta Campaign.
FORM = [
    ("general", "General", [
        ("general", "General", ["sanidi_campaignname", "ownerid", "sanidi_campaignid", "sanidi_adaccountid",
                                "sanidi_objective", "sanidi_objectivev2type", "sanidi_promotiontype",
                                "sanidi_objectiveautogenerated"]),
        ("status", "Status", ["sanidi_status", "sanidi_deliverystatus", "sanidi_creationstate", "sanidi_deleted"]),
        ("schedule", "Schedule", ["sanidi_starttime", "sanidi_endtime", "sanidi_createdat", "sanidi_updatedat"]),
    ]),
    ("budgetbidding", "Budget & Bidding", [
        ("budget", "Budget", ["sanidi_dailybudget", "sanidi_lifetimespendcap", "sanidi_pacinglevel",
                              "sanidi_pacingpropertiesversion"]),
        ("bidding", "Bidding", ["sanidi_buymodel", "sanidi_reservedtype", "sanidi_autobidmaxbid"]),
        ("smartbudget", "Smart Budget", ["sanidi_sharedconversionlocation", "sanidi_sharedconversionwindow",
                                         "sanidi_sharedoptimizationgoal", "sanidi_sharedadsquadbidstrategy",
                                         "sanidi_sharedtargetcost", "sanidi_sharedpixelid"]),
    ]),
    ("measurementcompliance", "Measurement & Compliance", [
        ("appmeasurement", "App & Measurement", ["sanidi_iosappid", "sanidi_androidappurl",
                                                 "sanidi_appoptimizationtype", "sanidi_skadnetworkstatus",
                                                 "sanidi_mobileappid", "sanidi_catalogid"]),
        ("compliance", "Compliance", ["sanidi_restricteddeliverysignals", "sanidi_candidateballotinformation"]),
    ]),
]

ACTIVE_VIEW_FIRST = ["sanidi_campaignname", "sanidi_status", "sanidi_deliverystatus", "sanidi_objective",
                     "sanidi_starttime", "sanidi_endtime", "sanidi_dailybudget", "sanidi_lifetimespendcap",
                     "sanidi_updatedat"]
INACTIVE_VIEW = ["sanidi_campaignname", "sanidi_status", "sanidi_updatedat", "createdon"]

SPEC = TableSpec(
    schema="sanidi_SnapCampaign",
    display="Snap Campaign",
    plural="Snap Campaigns",
    description="Snapchat campaigns synced from the Snapchat Marketing API by the Get Snap Campaigns flow.",
    fields=FIELDS,
    form=FORM,
    active_view_first=ACTIVE_VIEW_FIRST,
    inactive_view=INACTIVE_VIEW,
    key_field="sanidi_campaignid",
    key_display="Campaign ID",
    optionsets={DELIVERY_OPTIONSET: ("Snap Campaign Delivery Status", DELIVERY_STATUS)},
    related=[RelatedGrid("snapadsquads", "Snap Ad Squads", "sanidi_snapadsquad",
                         "sanidi_snapadsquad_snapcampaign_sanidi_snapcampaign",
                         view_id_for("sanidi_snapadsquad", "Active Snap Ad Squads"))],
)

if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--template", required=True, help="Solution export with the Meta template tables")
    ap.add_argument("--out", default="SnapCampaignTable.zip")
    a = ap.parse_args()
    build_package(SPEC, a.template, a.out)
