"""Builds an unmanaged solution package that creates the "Snap Campaign" table
(sanidi_SnapCampaign) in the "AlSanidi | Marketing" solution, with its columns,
choices, alternate key, main form and views.

The Dataverse XML format is taken from the existing Meta Campaign table
(sanidi_MetaCampaign) in an export of the solution, so the new table matches its
conventions. Field definitions come from
https://developers.snap.com/marketing-api/Ads-API/campaigns.

Run:
  pac solution export --name AlSanidiMarketing --path AlSanidiMarketing.zip --environment <env>
  python3 build_table_solution.py --template AlSanidiMarketing.zip [--out SnapCampaignTable.zip]
  pac solution import --path SnapCampaignTable.zip --environment <env>

The package contains only the new table and its delivery-status option set, so
importing it leaves the rest of the solution untouched. IDs are deterministic, so
re-importing updates the same table, form and views.
"""
import argparse
import re
import uuid
import zipfile
from xml.sax.saxutils import escape

SCHEMA = "sanidi_SnapCampaign"
LOGICAL = SCHEMA.lower()
DISPLAY, PLURAL = "Snap Campaign", "Snap Campaigns"
DESCRIPTION = "Snapchat campaigns synced from the Snapchat Marketing API by the Get Snap Campaigns flow."
DELIVERY_OPTIONSET = "sanidi_snapcampaigndeliverystatus"

TEMPLATE_SCHEMA = "sanidi_MetaCampaign"
TEMPLATE_LOGICAL = TEMPLATE_SCHEMA.lower()

DELIVERY_STATUS = [
    "PENDING", "VALID", "DELIVERING", "INVALID_NOT_ACTIVE", "INVALID_NOT_EFFECTIVE_ACTIVE",
    "INVALID_START_TIME", "INVALID_END_TIME", "INVALID_EFFECTIVE_START_TIME", "INVALID_EFFECTIVE_END_TIME",
    "INVALID_EFFECTIVE_DELETED", "INVALID_EFFECTIVE_INVALID", "INVALID_START_TIME_AFTER_END_TIME",
    "INVALID_UNKNOWN", "INVALID_CAMPAIGN_LIFETIME_SPEND_CAP",
    "INVALID_OVER_BUDGET_CAMPAIGN_FINALIZED_LIFETIME_SPEND", "INVALID_OVER_BUDGET_CAMPAIGN_REALTIME_LIFETIME_SPEND",
    "INVALID_OVER_BUDGET_CAMPAIGN_DAILY_SPEND", "NO_VALID_AD_SQUAD", "INVALID_RF_FOR_RESERVED_BUY",
    "INVALID_UNKNOWN_FORECAST_ERROR", "INVALID_CAMPAIGN_HAS_NO_ACTIVE_AD_SQUAD", "INVALID_TEST_ACCOUNT",
]

# (logical name, display name, type, extra, description). Types: text, choice, multichoice, bool,
# datetime, money, int. extra = max length for text, option labels for choice.
FIELDS = [
    ("sanidi_campaignname", "Campaign Name", "text", 375, "Snap: name"),
    ("sanidi_campaignid", "Campaign ID", "text", 100, "Snap: id"),
    ("sanidi_adaccountid", "Ad Account ID", "text", 100, "Snap: ad_account_id"),
    ("sanidi_objective", "Objective", "choice",
     ["BRAND_AWARENESS", "APP_CONVERSION", "APP_INSTALL", "CATALOG_SALES", "ENGAGEMENT", "LEAD_GENERATION",
      "VIDEO_VIEW", "WEB_CONVERSION", "PROMOTE_STORIES", "PROMOTE_PLACES"], "Snap: objective (legacy)"),
    ("sanidi_objectivev2type", "Objective V2 Type", "choice",
     ["AWARENESS_AND_ENGAGEMENT", "SALES", "TRAFFIC", "APP_PROMOTION", "LEADS"],
     "Snap: objective_v2_properties.objective_v2_type"),
    ("sanidi_promotiontype", "Promotion Type", "choice",
     ["PROMOTE_PLACES", "PROMOTE_SHOWS", "APP_INSTALL", "APP_REENGAGEMENT"],
     "Snap: objective_v2_properties.promotion_type"),
    ("sanidi_objectiveautogenerated", "Objective Auto Generated", "bool", None,
     "Snap: objective_v2_properties.is_auto_generated"),
    ("sanidi_status", "Status", "choice", ["ACTIVE", "PAUSED"], "Snap: status"),
    ("sanidi_deliverystatus", "Delivery Status", "multichoice", DELIVERY_STATUS, "Snap: delivery_status"),
    ("sanidi_creationstate", "Creation State", "text", 100, "Snap: creation_state"),
    ("sanidi_deleted", "Deleted", "bool", None, "Snap: deleted"),
    ("sanidi_starttime", "Start Time", "datetime", None, "Snap: start_time"),
    ("sanidi_endtime", "End Time", "datetime", None, "Snap: end_time"),
    ("sanidi_createdat", "Created At", "datetime", None, "Snap: created_at"),
    ("sanidi_updatedat", "Updated At", "datetime", None, "Snap: updated_at"),
    ("sanidi_dailybudget", "Daily Budget", "money", None, "Snap: daily_budget_micro / 1,000,000"),
    ("sanidi_lifetimespendcap", "Lifetime Spend Cap", "money", None, "Snap: lifetime_spend_cap_micro / 1,000,000"),
    ("sanidi_pacinglevel", "Pacing Level", "choice", ["AD_SQUAD", "CAMPAIGN"], "Snap: pacing_level"),
    ("sanidi_pacingpropertiesversion", "Pacing Properties Version", "int", None, "Snap: pacing_properties_version"),
    ("sanidi_buymodel", "Buy Model", "choice", ["AUCTION", "RESERVED"], "Snap: buy_model"),
    ("sanidi_reservedtype", "Reserved Type", "choice", ["REACH_AND_FREQUENCY"], "Snap: reserved_type"),
    ("sanidi_autobidmaxbid", "Auto Bid Max Bid", "money", None, "Snap: auto_bid_max_bid_micro / 1,000,000"),
    ("sanidi_sharedconversionlocation", "Shared Conversion Location", "choice",
     ["APP", "WEB", "CALL", "TEXT", "LEAD_FORM"], "Snap: shared_properties.shared_conversion_location"),
    ("sanidi_sharedconversionwindow", "Shared Conversion Window", "text", 100,
     "Snap: shared_properties.shared_conversion_window"),
    ("sanidi_sharedoptimizationgoal", "Shared Optimization Goal", "text", 100,
     "Snap: shared_properties.shared_optimization_goal"),
    ("sanidi_sharedadsquadbidstrategy", "Shared Ad Squad Bid Strategy", "choice",
     ["AUTO_BID", "LOWEST_COST_WITH_MAX_BID", "TARGET_COST"], "Snap: shared_properties.shared_ad_squad_bid_strategy"),
    ("sanidi_sharedtargetcost", "Shared Target Cost", "money", None,
     "Snap: shared_properties.target_cost_in_micro / 1,000,000"),
    ("sanidi_sharedpixelid", "Shared Pixel ID", "text", 100, "Snap: shared_properties.shared_pixel_id"),
    ("sanidi_iosappid", "iOS App ID", "text", 100, "Snap: measurement_spec.ios_app_id"),
    ("sanidi_androidappurl", "Android App URL", "text", 200, "Snap: measurement_spec.android_app_url"),
    ("sanidi_appoptimizationtype", "App Optimization Type", "choice",
     ["SKAN", "UNIFIED", "UNIFIED_WITH_SKAN_MEASURE"], "Snap: mobile_app_properties.app_optimization_type"),
    ("sanidi_skadnetworkstatus", "SKAdNetwork Status", "choice", ["ENROLLED", "NOT_ENROLLED"],
     "Snap: mobile_app_properties.skad_network_status"),
    ("sanidi_mobileappid", "Mobile App ID", "text", 100, "Snap: mobile_app_properties.mobile_app_id"),
    ("sanidi_catalogid", "Catalog ID", "text", 100, "Snap: product_properties.catalog_id"),
    ("sanidi_restricteddeliverysignals", "Restricted Delivery Signals", "bool", None,
     "Snap: regulations.restricted_delivery_signals"),
    ("sanidi_candidateballotinformation", "Candidate Ballot Information", "text", 500,
     "Snap: regulations.candidate_ballot_information"),
]
F = {f[0]: f for f in FIELDS}

# Main form: tab -> [(section name, label, [fields])]; "ownerid" sits in General like Meta Campaign.
FORM = [
    ("general", "General", [
        ("general", "General", ["sanidi_campaignname", "ownerid", "sanidi_campaignid", "sanidi_adaccountid",
                                "sanidi_objective", "sanidi_objectivev2type", "sanidi_promotiontype",
                                "sanidi_objectiveautogenerated"]),
        ("status", "Status", ["sanidi_status", "sanidi_deliverystatus", "sanidi_creationstate", "sanidi_deleted"]),
        ("schedule", "Schedule", ["sanidi_starttime", "sanidi_endtime", "sanidi_createdat", "sanidi_updatedat"]),
    ]),
    ("budgetbidding", "Budget & Bidding", [
        ("budget", "Budget", ["sanidi_dailybudget", "sanidi_lifetimespendcap", "sanidi_pacinglevel",
                              "sanidi_pacingpropertiesversion"]),
        ("bidding", "Bidding", ["sanidi_buymodel", "sanidi_reservedtype", "sanidi_autobidmaxbid"]),
        ("smartbudget", "Smart Budget", ["sanidi_sharedconversionlocation", "sanidi_sharedconversionwindow",
                                         "sanidi_sharedoptimizationgoal", "sanidi_sharedadsquadbidstrategy",
                                         "sanidi_sharedtargetcost", "sanidi_sharedpixelid"]),
    ]),
    ("measurementcompliance", "Measurement & Compliance", [
        ("appmeasurement", "App & Measurement", ["sanidi_iosappid", "sanidi_androidappurl",
                                                 "sanidi_appoptimizationtype", "sanidi_skadnetworkstatus",
                                                 "sanidi_mobileappid", "sanidi_catalogid"]),
        ("compliance", "Compliance", ["sanidi_restricteddeliverysignals", "sanidi_candidateballotinformation"]),
    ]),
]

ACTIVE_VIEW_FIRST = ["sanidi_campaignname", "sanidi_status", "sanidi_deliverystatus", "sanidi_objective",
                     "sanidi_starttime", "sanidi_endtime", "sanidi_dailybudget", "sanidi_lifetimespendcap",
                     "sanidi_updatedat"]
INACTIVE_VIEW = ["sanidi_campaignname", "sanidi_status", "sanidi_updatedat", "createdon"]

CLASSIDS = {
    "text": "{4273EDBD-AC1D-40d3-9FB2-095C621B552D}", "choice": "{3EF39988-22BB-4F0B-BBBE-64B5A3748AEE}",
    "multichoice": "{4AA28AB7-9C13-4F57-A73D-AD894D048B5F}", "bool": "{67FAC785-CD58-4F9F-ABB3-4B7DDC6ED5ED}",
    "datetime": "{5B773807-9FB2-42db-97C3-7A91EFF8ADFF}", "money": "{533B9E00-756B-4312-95A0-DC888637AC78}",
    "int": "{C6D124CA-7EDA-4a60-AEA9-7FB8D318B68F}", "owner": "{270BD3DB-D9AF-4782-9025-509E298DEC0A}",
}


def gid(name):
    return "{%s}" % uuid.uuid5(uuid.NAMESPACE_URL, f"alsanidi/{LOGICAL}/{name}")


def attr_blocks(xml):
    return {m.group(2): m.group(1) for m in
            re.finditer(r'(<attribute PhysicalName="([^"]+)">.*?</attribute>)', xml, re.S)}


def set_tag(block, tag, value):
    return re.sub(rf"<{tag}>[^<]*</{tag}>", f"<{tag}>{value}</{tag}>", block, count=1)


def labels(display, desc):
    return (f'<displaynames>\n                <displayname description="{escape(display)}" languagecode="1033" />\n'
            f'              </displaynames>\n              <Descriptions>\n'
            f'                <Description description="{escape(desc)}" languagecode="1033" />\n'
            f'              </Descriptions>')


def option_xml(values, indent):
    pad = " " * indent
    out = []
    for i, v in enumerate(values, start=1):
        out.append(f'{pad}<option value="{i}" ExternalValue="" IsHidden="0">\n'
                   f'{pad}  <labels>\n{pad}    <label description="{escape(v)}" languagecode="1033" />\n'
                   f'{pad}  </labels>\n{pad}  <Descriptions>\n'
                   f'{pad}    <Description description="" languagecode="1033" />\n{pad}  </Descriptions>\n'
                   f'{pad}</option>')
    return "\n".join(out)


def rename(block, old, new):
    return block.replace(f'PhysicalName="{old}"', f'PhysicalName="{new}"') \
                .replace(f"<Name>{old.lower()}</Name>", f"<Name>{new}</Name>") \
                .replace(f"<LogicalName>{old.lower()}</LogicalName>", f"<LogicalName>{new}</LogicalName>")


def build_attribute(t, field, multi_template):
    name, display, kind, extra, desc = field
    src = {"text": "sanidi_accountid", "choice": "sanidi_bidstrategy", "bool": "sanidi_adsetbudgetsharingenabled",
           "datetime": "sanidi_starttime", "money": "sanidi_budgetremaining", "int": "sanidi_toplineid"}
    if name == "sanidi_campaignname":
        b = t["sanidi_campaignname"]
    elif kind == "multichoice":
        b = rename(multi_template, re.search(r'PhysicalName="([^"]+)"', multi_template).group(1), name)
        b = set_tag(b, "OptionSetName", DELIVERY_OPTIONSET)
    else:
        b = rename(t[src[kind]], src[kind], name)
    b = re.sub(r"<displaynames>.*?</Descriptions>", labels(display, desc), b, count=1, flags=re.S)
    if kind == "text":
        b = set_tag(set_tag(b, "MaxLength", extra), "Length", extra * 2)
    if kind in ("choice", "bool"):
        b = re.sub(r'<optionset Name="[^"]+">', f'<optionset Name="{LOGICAL}_{name}">', b, count=1)
        b = re.sub(r"(<optionset .*?<displaynames>\s*<displayname description=\")[^\"]*",
                   lambda m: m.group(1) + escape(display), b, count=1, flags=re.S)
    if kind == "choice":
        b = re.sub(r"<options>.*?</options>", "<options>\n" + option_xml(extra, 18) + "\n                </options>",
                   b, count=1, flags=re.S)
    blocks = [b]
    if kind == "money":
        base = rename(t["sanidi_budgetremaining_Base"], "sanidi_budgetremaining_Base", f"{name}_Base")
        base = base.replace(f"<Name>{name}_Base</Name>", f"<Name>{name}_base</Name>") \
                   .replace(f"<LogicalName>{name}_Base</LogicalName>", f"<LogicalName>{name}_base</LogicalName>")
        base = set_tag(base, "CalculationOf", name)
        base = re.sub(r"<displaynames>.*?</Descriptions>",
                      labels(f"{display} (Base)", f"Value of the {display} in base currency."), base,
                      count=1, flags=re.S)
        blocks.append(base)
    return blocks


def form_xml():
    tabs = []
    for tab_name, tab_label, sections in FORM:
        width = f"{100 // len(sections)}%"
        cols = []
        for sec_name, sec_label, fields in sections:
            rows = []
            for f in fields:
                kind = "owner" if f == "ownerid" else F[f][2]
                label = "Owner" if f == "ownerid" else F[f][1]
                rows.append(
                    f'<row><cell id="{gid("cell/" + f)}"><labels><label description="{escape(label)}" '
                    f'languagecode="1033" /></labels><control id="{f}" classid="{CLASSIDS[kind]}" '
                    f'datafieldname="{f}" /></cell></row>')
            cols.append(
                f'<column width="{width}"><sections><section name="{sec_name}" showlabel="true" showbar="false" '
                f'IsUserDefined="0" id="{gid("section/" + sec_name)}" columns="1" labelwidth="200"><labels>'
                f'<label description="{escape(sec_label)}" languagecode="1033" /></labels><rows>{"".join(rows)}'
                f'</rows></section></sections></column>')
        tabs.append(
            f'<tab name="{tab_name}" verticallayout="true" id="{gid("tab/" + tab_name)}" IsUserDefined="1" '
            f'expanded="true" showlabel="true"><labels><label description="{escape(tab_label)}" '
            f'languagecode="1033" /></labels><columns>{"".join(cols)}</columns></tab>')
    return f"""<FormXml>
        <forms type="main">
          <systemform>
            <formid>{gid("form/main")}</formid>
            <IntroducedVersion>1.0.0</IntroducedVersion>
            <FormPresentation>1</FormPresentation>
            <FormActivationState>1</FormActivationState>
            <form headerdensity="HighWithControls">
              <tabs>{"".join(tabs)}</tabs>
              <DisplayConditions Order="0" FallbackForm="true">
                <Everyone />
              </DisplayConditions>
            </form>
            <IsCustomizable>1</IsCustomizable>
            <CanBeDeleted>1</CanBeDeleted>
            <LocalizedNames>
              <LocalizedName description="Information" languagecode="1033" />
            </LocalizedNames>
            <Descriptions>
              <Description description="A form for this entity." languagecode="1033" />
            </Descriptions>
          </systemform>
        </forms>
      </FormXml>"""


def view_columns(q, columns):
    pk = f"{LOGICAL}id"
    widths = {"sanidi_campaignname": 300, "createdon": 125}
    cells = "".join(f'<cell name="{c}" width="{widths.get(c, 150)}" />' for c in columns)
    q = re.sub(r'<row name="result" id="[^"]+">.*?</row>', f'<row name="result" id="{pk}">{cells}</row>',
               q, count=1, flags=re.S)
    attrs = "".join(f'<attribute name="{c}" />' for c in [pk] + columns)
    q = re.sub(r'\s*<attribute name="[^"]+" />', "", q)
    return re.sub(r'(<entity name="[^"]+">)', rf"\g<1>{attrs}", q, count=1)


def saved_queries(template_entity):
    out = []
    for i, q in enumerate(re.findall(r"<savedquery>.*?</savedquery>", template_entity, re.S)):
        name = re.search(r'<LocalizedName description="([^"]+)" languagecode="1033"', q).group(1)
        q = q.replace(TEMPLATE_LOGICAL, LOGICAL).replace("Meta Campaigns", PLURAL).replace("Meta Campaign", DISPLAY)
        q = re.sub(r'<LocalizedName description="[^"]*" languagecode="1025" />\s*', "", q)
        q = re.sub(r"<savedqueryid>[^<]+</savedqueryid>", f"<savedqueryid>{gid('view/' + name)}</savedqueryid>", q)
        if name.startswith("Active"):
            q = view_columns(q, ACTIVE_VIEW_FIRST + [f[0] for f in FIELDS if f[0] not in ACTIVE_VIEW_FIRST])
        elif name.startswith("Inactive"):
            q = view_columns(q, INACTIVE_VIEW)
        else:
            keep = [c for c in re.findall(r'<cell name="([^"]+)"', q) if c in F or not c.startswith("sanidi_")]
            q = view_columns(q, keep or ["sanidi_campaignname"])
        out.append(q)
    return "<SavedQueries>\n        <savedqueries>\n          " + "\n          ".join(out) + \
           "\n        </savedqueries>\n      </SavedQueries>"


def entity_key():
    return f"""<EntityKeys>
            <EntityKey>
              <Name>{SCHEMA}_CampaignIdKey</Name>
              <LogicalName>{LOGICAL}_campaignidkey</LogicalName>
              <IntroducedVersion>1.0.0</IntroducedVersion>
              <IsCustomizable>1</IsCustomizable>
              <EntityKeyAttributes>
                <AttributeName>sanidi_campaignid</AttributeName>
              </EntityKeyAttributes>
              <displaynames>
                <displayname description="Campaign ID Key" languagecode="1033" />
              </displaynames>
            </EntityKey>
          </EntityKeys>
          """


def build(template_zip, out):
    src = zipfile.ZipFile(template_zip)
    c = src.read("customizations.xml").decode("utf-8-sig")
    start = c.index(f">{TEMPLATE_SCHEMA}</Name>")
    ent = c[c.rindex("<Entity>", 0, start):c.index("</Entity>", start) + len("</Entity>")]
    t = attr_blocks(ent)
    multi = re.search(r'<attribute PhysicalName="[^"]+">\s*<Type>multiselectpicklist</Type>.*?</attribute>',
                      c, re.S).group(0)

    # System columns (owner, created/modified, currency, state...) carried over from the template.
    system = [b for n, b in t.items() if not n.startswith("sanidi_")]
    pk = rename(t[f"{TEMPLATE_SCHEMA}Id"], f"{TEMPLATE_SCHEMA}Id", f"{SCHEMA}Id") \
        .replace(f"<Name>{SCHEMA}Id</Name>", f"<Name>{LOGICAL}id</Name>") \
        .replace(f"<LogicalName>{SCHEMA}Id</LogicalName>", f"<LogicalName>{LOGICAL}id</LogicalName>")
    pk = re.sub(r"<displaynames>.*?</displaynames>",
                f'<displaynames>\n                <displayname description="{DISPLAY}" languagecode="1033" />\n'
                f"              </displaynames>", pk, count=1, flags=re.S)
    custom = [b for f in FIELDS for b in build_attribute(t, f, multi)]
    attributes = "<attributes>\n            " + "\n            ".join(system + [pk] + custom) + \
                 "\n          </attributes>"

    head = ent[:ent.index("<attributes>")]
    head = re.sub(r"<LocalizedNames>.*?</Descriptions>",
                  f'<LocalizedNames>\n            <LocalizedName description="{DISPLAY}" languagecode="1033" />\n'
                  f'          </LocalizedNames>\n          <LocalizedCollectionNames>\n'
                  f'            <LocalizedCollectionName description="{PLURAL}" languagecode="1033" />\n'
                  f'          </LocalizedCollectionNames>\n          <Descriptions>\n'
                  f'            <Description description="{escape(DESCRIPTION)}" languagecode="1033" />\n'
                  f"          </Descriptions>", head, count=1, flags=re.S)
    info_tail = ent[ent.index("</attributes>") + len("</attributes>"):ent.index("</EntityInfo>")]
    info_tail = re.sub(r"\s*<EntityKeys>.*?</EntityKeys>", "", info_tail, flags=re.S)
    info_tail = set_tag(info_tail, "EntitySetName", f"{LOGICAL}s")
    ribbon = re.search(r"<RibbonDiffXml>.*?</RibbonDiffXml>", ent, re.S).group(0)
    entity = (head + attributes + "\n          " + entity_key() + info_tail.lstrip() + "</EntityInfo>\n      "
              + form_xml() + "\n      " + saved_queries(ent) + "\n      " + ribbon + "\n    </Entity>")
    entity = entity.replace(TEMPLATE_SCHEMA, SCHEMA).replace(TEMPLATE_LOGICAL, LOGICAL) \
                   .replace("Meta Campaigns", PLURAL).replace("Meta Campaign", DISPLAY)

    rel_names = [f"business_unit_{TEMPLATE_LOGICAL}", f"lk_{TEMPLATE_LOGICAL}_createdby",
                 f"lk_{TEMPLATE_LOGICAL}_modifiedby", f"owner_{TEMPLATE_LOGICAL}", f"team_{TEMPLATE_LOGICAL}",
                 f"TransactionCurrency_{TEMPLATE_SCHEMA}", f"user_{TEMPLATE_LOGICAL}"]
    rels = [re.search(rf'<EntityRelationship Name="{n}">.*?</EntityRelationship>', c, re.S).group(0)
            .replace(TEMPLATE_SCHEMA, SCHEMA).replace(TEMPLATE_LOGICAL, LOGICAL) for n in rel_names]

    optionset = f"""<optionset Name="{DELIVERY_OPTIONSET}" localizedName="Snap Campaign Delivery Status">
      <OptionSetType>picklist</OptionSetType>
      <IsGlobal>1</IsGlobal>
      <IntroducedVersion>1.0.0</IntroducedVersion>
      <IsCustomizable>1</IsCustomizable>
      <ExternalTypeName></ExternalTypeName>
      <displaynames>
        <displayname description="Snap Campaign Delivery Status" languagecode="1033" />
      </displaynames>
      <Descriptions>
        <Description description="Snapchat campaign delivery_status values" languagecode="1033" />
      </Descriptions>
      <options>
{option_xml(DELIVERY_STATUS, 8)}
      </options>
    </optionset>"""

    root_open = re.match(r".*?<ImportExportXml[^>]*>", c, re.S).group(0)
    customizations = (f"{root_open}\n  <Entities>\n    {entity}\n  </Entities>\n  <Roles />\n  <Workflows />\n"
                      f"  <FieldSecurityProfiles />\n  <Templates />\n  <EntityMaps />\n  <EntityRelationships>\n    "
                      + "\n    ".join(rels) + "\n  </EntityRelationships>\n  <OrganizationSettings />\n"
                      f"  <optionsets>\n    {optionset}\n  </optionsets>\n  <CustomControls />\n"
                      f"  <EntityDataProviders />\n  <Languages>\n    <Language>1033</Language>\n  </Languages>\n"
                      f"</ImportExportXml>\n")

    solution = src.read("solution.xml").decode("utf-8-sig")
    solution = re.sub(r"<RootComponents>.*?</RootComponents>",
                      f'<RootComponents>\n      <RootComponent type="1" schemaName="{LOGICAL}" behavior="0" />\n'
                      f'      <RootComponent type="9" schemaName="{DELIVERY_OPTIONSET}" behavior="0" />\n'
                      f"    </RootComponents>", solution, count=1, flags=re.S)
    solution = re.sub(r"<MissingDependencies>.*?</MissingDependencies>", "<MissingDependencies />",
                      solution, count=1, flags=re.S)

    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr("[Content_Types].xml", src.read("[Content_Types].xml"))
        z.writestr("solution.xml", solution)
        z.writestr("customizations.xml", customizations)
    print(f"Wrote {out}: {len(FIELDS)} columns, {len(rels)} system relationships")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--template", required=True, help="Exported AlSanidiMarketing solution zip")
    ap.add_argument("--out", default="SnapCampaignTable.zip")
    a = ap.parse_args()
    build(a.template, a.out)
