"""Builds an unmanaged solution package that adds the "Get Snap Campaigns" cloud flow
to the "AlSanidi | Marketing" solution.

The flow follows the Meta "Get Campaigns" flow: a manual trigger, the custom connector
to read campaigns, choice labels mapped to their option values, and a List rows check
on Campaign ID that decides between updating the existing row and adding a new one.
It reads every ad account the Snap connection can see (organizations -> ad accounts ->
campaigns) and writes to the Snap Campaign table (sanidi_snapcampaign).

Run:
  pac solution export --name AlSanidiMarketing --path AlSanidiMarketing.zip --environment <env>
  python3 build_flow_solution.py --template AlSanidiMarketing.zip [--out GetSnapCampaignsFlow.zip]
  pac solution import --path GetSnapCampaignsFlow.zip --environment <env>

The package holds only the flow; it reuses the existing Snap and Dataverse connection
references. IDs are deterministic, so
re-importing updates the same flow.
"""
import argparse
import json
import re
import uuid
import zipfile

from build_table_solution import DELIVERY_STATUS, FIELDS
from table_builder import solution_xml

FLOW_NAME = "Get Snap Campaigns"
FLOW_ID = str(uuid.uuid5(uuid.NAMESPACE_URL, "alsanidi/flows/get-snap-campaigns"))
TABLE_SET = "sanidi_snapcampaigns"
SNAP_API = "shared_sanidi-5fsnap-5f43b530b23a0dc933"
from flow_builder import SNAP_CONNREF  # noqa: E402  (shared with the other Snap flows)
DATAVERSE_API = "shared_commondataserviceforapps"
DATAVERSE_CONNREF = "sanidi_sharedcommondataserviceforapps_79822"

# Where each column's value sits in a Snap campaign object (path from the campaign root).
SOURCE = {
    "sanidi_campaignname": ["name"],
    "sanidi_campaignid": ["id"],
    "sanidi_adaccountid": ["ad_account_id"],
    "sanidi_objective": ["objective"],
    "sanidi_objectivev2type": ["objective_v2_properties", "objective_v2_type"],
    "sanidi_promotiontype": ["objective_v2_properties", "promotion_type"],
    "sanidi_objectiveautogenerated": ["objective_v2_properties", "is_auto_generated"],
    "sanidi_status": ["status"],
    "sanidi_deliverystatus": ["delivery_status"],
    "sanidi_creationstate": ["creation_state"],
    "sanidi_deleted": ["deleted"],
    "sanidi_starttime": ["start_time"],
    "sanidi_endtime": ["end_time"],
    "sanidi_createdat": ["created_at"],
    "sanidi_updatedat": ["updated_at"],
    "sanidi_dailybudget": ["daily_budget_micro"],
    "sanidi_lifetimespendcap": ["lifetime_spend_cap_micro"],
    "sanidi_pacinglevel": ["pacing_level"],
    "sanidi_pacingpropertiesversion": ["pacing_properties_version"],
    "sanidi_buymodel": ["buy_model"],
    "sanidi_reservedtype": ["reserved_type"],
    "sanidi_autobidmaxbid": ["auto_bid_max_bid_micro"],
    "sanidi_sharedconversionlocation": ["shared_properties", "shared_conversion_location"],
    "sanidi_sharedconversionwindow": ["shared_properties", "shared_conversion_window"],
    "sanidi_sharedoptimizationgoal": ["shared_properties", "shared_optimization_goal"],
    "sanidi_sharedadsquadbidstrategy": ["shared_properties", "shared_ad_squad_bid_strategy"],
    "sanidi_sharedtargetcost": ["shared_properties", "target_cost_in_micro"],
    "sanidi_sharedpixelid": ["shared_properties", "shared_pixel_id"],
    "sanidi_iosappid": ["measurement_spec", "ios_app_id"],
    "sanidi_androidappurl": ["measurement_spec", "android_app_url"],
    "sanidi_appoptimizationtype": ["mobile_app_properties", "app_optimization_type"],
    "sanidi_skadnetworkstatus": ["mobile_app_properties", "skad_network_status"],
    "sanidi_mobileappid": ["mobile_app_properties", "mobile_app_id"],
    "sanidi_catalogid": ["product_properties", "catalog_id"],
    "sanidi_restricteddeliverysignals": ["regulations", "restricted_delivery_signals"],
    "sanidi_candidateballotinformation": ["regulations", "candidate_ballot_information"],
}
assert set(SOURCE) == {f[0] for f in FIELDS}, "every table column needs a source"

# Snap's docs spell this value both ways; accept either.
EXTRA_LABELS = {"sanidi_sharedadsquadbidstrategy": {"AUTOBID": 1}}


def choice_maps():
    maps = {}
    for name, _, kind, extra, _ in FIELDS:
        if kind in ("choice", "multichoice"):
            labels = extra[1] if kind == "multichoice" else extra
            maps[name] = {label: i for i, label in enumerate(labels, start=1)}
            maps[name].update(EXTRA_LABELS.get(name, {}))
    return maps


def src(path):
    return "outputs('Campaign')" + "".join(f"?['{p}']" for p in path)


def value_expr(field):
    name, _, kind, _, _ = field
    s = src(SOURCE[name])
    if kind == "choice":
        return f"@outputs('Choice_maps')?['{name}']?[string({s})]"
    if kind == "multichoice":
        return "@if(empty(body('Known_delivery_status')), null, join(body('Known_delivery_status'), ','))"
    if kind == "money":
        return f"@if(equals({s}, null), null, div(float({s}), 1000000))"
    return f"@{s}"


def dataverse(operation, params):
    return {"type": "OpenApiConnection", "inputs": {
        "parameters": params,
        "host": {"apiId": f"/providers/Microsoft.PowerApps/apis/{DATAVERSE_API}",
                 "operationId": operation, "connectionName": DATAVERSE_API}}}


def snap(operation, params):
    return {"type": "OpenApiConnection", "inputs": {
        "parameters": params,
        "host": {"apiId": f"/providers/Microsoft.PowerApps/apis/{SNAP_API}",
                 "operationId": operation, "connectionName": SNAP_API}}}


def definition():
    columns = {f"item/{f[0]}": value_expr(f) for f in FIELDS}
    campaign_actions = {
        "Campaign": {"type": "Compose", "inputs": "@items('For_each_campaign')?['campaign']", "runAfter": {}},
        "Delivery_status_values": {
            "type": "Select", "runAfter": {"Campaign": ["Succeeded"]},
            "inputs": {"from": f"@coalesce({src(['delivery_status'])}, json('[]'))",
                       "select": "@outputs('Choice_maps')?['sanidi_deliverystatus']?[item()]"}},
        "Known_delivery_status": {
            "type": "Query", "runAfter": {"Delivery_status_values": ["Succeeded"]},
            "inputs": {"from": "@body('Delivery_status_values')", "where": "@not(equals(item(), null))"}},
        "Find_existing_campaign": {
            **dataverse("ListRecords", {
                "entityName": TABLE_SET,
                "$select": "sanidi_snapcampaignid",
                "$filter": f"sanidi_campaignid eq '@{{{src(['id'])}}}'",
                "$top": 1}),
            "runAfter": {"Known_delivery_status": ["Succeeded"]}},
        "If_campaign_exists": {
            "type": "If", "runAfter": {"Find_existing_campaign": ["Succeeded"]},
            "expression": {"and": [{"greater": ["@length(outputs('Find_existing_campaign')?['body/value'])", 0]}]},
            "actions": {"Update_campaign": {**dataverse("UpdateOnlyRecord", {
                "entityName": TABLE_SET,
                "recordId": "@first(outputs('Find_existing_campaign')?['body/value'])?['sanidi_snapcampaignid']",
                **columns}), "runAfter": {}}},
            "else": {"actions": {"Add_campaign": {**dataverse("CreateRecord", {
                "entityName": TABLE_SET, **columns}), "runAfter": {}}}}},
    }
    return {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "contentVersion": "1.0.0.0",
        "parameters": {"$connections": {"defaultValue": {}, "type": "Object"},
                       "$authentication": {"defaultValue": {}, "type": "SecureObject"}},
        "triggers": {"manual": {"type": "Request", "kind": "Button", "inputs": {
            "schema": {"type": "object", "properties": {}, "required": []}}}},
        "actions": {
            "Choice_maps": {"type": "Compose", "inputs": choice_maps(), "runAfter": {},
                            "description": "Snap value -> Dataverse option value for every choice column"},
            "List_organizations": {**snap("ListOrganizations", {"with_ad_accounts": True}),
                                   "runAfter": {"Choice_maps": ["Succeeded"]}},
            "For_each_organization": {
                "type": "Foreach", "foreach": "@outputs('List_organizations')?['body/organizations']",
                "runAfter": {"List_organizations": ["Succeeded"]},
                "actions": {"For_each_ad_account": {
                    "type": "Foreach", "runAfter": {},
                    "foreach": "@coalesce(items('For_each_organization')?['organization']?['ad_accounts'], json('[]'))",
                    "actions": {
                        "List_campaigns": {**snap("ListCampaigns", {
                            "ad_account_id": "@items('For_each_ad_account')?['id']"}), "runAfter": {}},
                        "For_each_campaign": {
                            "type": "Foreach", "foreach": "@outputs('List_campaigns')?['body/campaigns']",
                            "runAfter": {"List_campaigns": ["Succeeded"]},
                            "actions": campaign_actions}}}}},
        },
    }


def flow_json():
    return {"properties": {
        "connectionReferences": {
            SNAP_API: {"runtimeSource": "embedded",
                       "connection": {"connectionReferenceLogicalName": SNAP_CONNREF},
                       "api": {"name": SNAP_API, "logicalName": "sanidi_snap"}},
            DATAVERSE_API: {"runtimeSource": "embedded",
                            "connection": {"connectionReferenceLogicalName": DATAVERSE_CONNREF},
                            "api": {"name": DATAVERSE_API}}},
        "definition": definition(),
        "templateName": ""},
        "schemaVersion": "1.0.0.0"}


CONTENT_TYPES = """<?xml version="1.0" encoding="utf-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="xml" ContentType="application/octet-stream" /><Default Extension="json" ContentType="application/octet-stream" /></Types>"""


def build(template_zip, out):
    src_zip = zipfile.ZipFile(template_zip)
    c = src_zip.read("customizations.xml").decode("utf-8-sig")
    root_open = re.match(r".*?<ImportExportXml[^>]*>", c, re.S).group(0)
    json_file = f"/Workflows/GetSnapCampaigns-{FLOW_ID.upper()}.json"
    customizations = f"""{root_open}
  <Entities />
  <Roles />
  <Workflows>
    <Workflow WorkflowId="{{{FLOW_ID}}}" Name="{FLOW_NAME}">
      <JsonFileName>{json_file}</JsonFileName>
      <Type>1</Type>
      <Subprocess>0</Subprocess>
      <Category>5</Category>
      <Mode>0</Mode>
      <Scope>4</Scope>
      <OnDemand>0</OnDemand>
      <TriggerOnCreate>0</TriggerOnCreate>
      <TriggerOnDelete>0</TriggerOnDelete>
      <AsyncAutodelete>0</AsyncAutodelete>
      <SyncWorkflowLogOnFailure>0</SyncWorkflowLogOnFailure>
      <StateCode>0</StateCode>
      <StatusCode>1</StatusCode>
      <RunAs>1</RunAs>
      <IsTransacted>1</IsTransacted>
      <IntroducedVersion>1.0.0</IntroducedVersion>
      <IsCustomizable>1</IsCustomizable>
      <BusinessProcessType>0</BusinessProcessType>
      <IsCustomProcessingStepAllowedForOtherPublishers>1</IsCustomProcessingStepAllowedForOtherPublishers>
      <ModernFlowType>0</ModernFlowType>
      <PrimaryEntity>none</PrimaryEntity>
      <LocalizedNames>
        <LocalizedName languagecode="1033" description="{FLOW_NAME}" />
      </LocalizedNames>
    </Workflow>
  </Workflows>
  <FieldSecurityProfiles />
  <Templates />
  <EntityMaps />
  <EntityRelationships />
  <OrganizationSettings />
  <optionsets />
  <CustomControls />
  <EntityDataProviders />
  <Languages>
    <Language>1033</Language>
  </Languages>
</ImportExportXml>
"""
    solution = solution_xml(src_zip.read("solution.xml").decode("utf-8-sig"),
                            [f'<RootComponent type="29" id="{{{FLOW_ID}}}" behavior="0" />'])
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr("[Content_Types].xml", CONTENT_TYPES)
        z.writestr("solution.xml", solution)
        z.writestr("customizations.xml", customizations)
        z.writestr(json_file.lstrip("/"), json.dumps(flow_json(), indent=2))
    print(f"Wrote {out}: flow {FLOW_ID}, {len(FIELDS)} mapped columns, "
          f"{len(DELIVERY_STATUS)} delivery status values")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--template", required=True, help="Exported AlSanidiMarketing solution zip")
    ap.add_argument("--out", default="GetSnapCampaignsFlow.zip")
    a = ap.parse_args()
    build(a.template, a.out)
